export const GET_COUNTRY_LIST = 'GET_COUNTRY_LIST';
export const GET_COUNTRY_LIST_SUCCESS = 'GET_COUNTRY_LIST_SUCCESS';
export const GET_COUNTRY_LIST_FAILURE = 'GET_COUNTRY_LIST_FAILURE';

export const GET_STATE_LIST = 'GET_STATE_LIST';
export const GET_STATE_LIST_SUCCESS = 'GET_STATE_LIST_SUCCESS';
export const GET_STATE_LIST_FAILURE = 'GET_STATE_LIST_FAILURE';

export const GET_CITY_LIST = 'GET_CITY_LIST';
export const GET_CITY_LIST_SUCCESS = 'GET_CITY_LIST_SUCCESS';
export const GET_CITY_LIST_FAILURE = 'GET_CITY_LIST_FAILURE';

export const GET_USER_TYPE_LIST = 'GET_USER_TYPE_LIST';
export const GET_USER_TYPE_LIST_SUCCESS = 'GET_USER_TYPE_LIST_SUCCESS';
export const GET_USER_TYPE_LIST_FAILURE = 'GET_USER_TYPE_LIST_FAILURE';

export const GET_ROLE_LIST = 'GET_ROLE_LIST';
export const GET_ROLE_LIST_SUCCESS = 'GET_ROLE_LIST_SUCCESS';
export const GET_ROLE_LIST_FAILURE = 'GET_ROLE_LIST_FAILURE';

export const GET_OFFICE_LIST = 'GET_OFFICE_LIST';
export const GET_OFFICE_LIST_SUCCESS = 'GET_OFFICE_LIST_SUCCESS';
export const GET_OFFICE_LIST_FAILURE = 'GET_OFFICE_LIST_FAILURE';

export const GET_DEPARTMENT_LIST = 'GET_DEPARTMENT_LIST';
export const GET_DEPARTMENT_LIST_SUCCESS = 'GET_DEPARTMENT_LIST_SUCCESS';
export const GET_DEPARTMENT_LIST_FAILURE = 'GET_DEPARTMENT_LIST_FAILURE';