// GET METHODS

export const GET_PURCHASE_PLAN_LIST = 'GET_PURCHASE_PLAN_LIST';
export const GET_PURCHASE_PLAN_LIST_SUCCESS = 'GET_PURCHASE_PLAN_LIST_SUCCESS';
export const GET_PURCHASE_PLAN_LIST_FAILURE = 'GET_PURCHASE_PLAN_LIST_FAILURE';

export const GET_STATIC_DATA_PURCHASE_PLAN = 'GET_STATIC_DATA_PURCHASE_PLAN';
export const GET_STATIC_DATA_PURCHASE_PLAN_SUCCESS = 'GET_STATIC_DATA_PURCHASE_PLAN_SUCCESS';
export const GET_STATIC_DATA_PURCHASE_PLAN_FAILURE = 'GET_STATIC_DATA_PURCHASE_PLAN_FAILURE';

export const GET_PURCHASE_PLAN_DATA = 'GET_PURCHASE_PLAN_DATA';
export const GET_PURCHASE_PLAN_DATA_SUCCESS = 'GET_PURCHASE_PLAN_DATA_SUCCESS';
export const GET_PURCHASE_PLAN_DATA_FAILURE  = 'GET_PURCHASE_PLAN_DATA_FAILURE';

// POST METHODS

export const POST_SAVE_PURCHASE_PLAN = 'POST_SAVE_PURCHASE_PLAN';
export const POST_SAVE_PURCHASE_PLAN_SUCCESS = 'POST_SAVE_PURCHASE_PLAN_SUCCESS';
export const POST_SAVE_PURCHASE_PLAN_FAILURE = 'POST_SAVE_PURCHASE_PLAN_FAILURE';

export const POST_DELETE_PURCHASE_PLAN = 'POST_DELETE_PURCHASE_PLAN';
export const POST_DELETE_PURCHASE_PLAN_SUCCESS = 'POST_DELETE_PURCHASE_PLAN_SUCCESS';
export const POST_DELETE_PURCHASE_PLAN_FAILURE = 'POST_DELETE_PURCHASE_PLAN_FAILURE';
