// GET METHODS

export const GET_USER_LIST = 'GET_USER_LIST';
export const GET_USER_LIST_SUCCESS = 'GET_USER_LIST_SUCCESS';
export const GET_USER_LIST_FAILURE = 'GET_USER_LIST_FAILURE';

export const GET_USER_DATA = 'GET_USER_DATA';
export const GET_USER_DATA_SUCCESS = 'GET_USER_DATA_SUCCESS';
export const GET_USER_DATA_FAILURE = 'GET_USER_DATA_FAILURE';

export const GET_BULKIMPORT_LIST = 'GET_BULKIMPORT_LIST';
export const GET_BULKIMPORT_LIST_SUCCESS = 'GET_BULKIMPORT_LIST_SUCCESS';
export const GET_BULKIMPORT_LIST_FAILURE = 'GET_BULKIMPORT_LIST_FAILURE';

export const GET_CUSTOMER_LIST = 'GET_CUSTOMER_LIST';
export const GET_CUSTOMER_LIST_SUCCESS = 'GET_CUSTOMER_LIST_SUCCESS';
export const GET_CUSTOMER_LIST_FAILURE = 'GET_CUSTOMER_LIST_FAILURE';


// POST METHODS
export const POST_LOGIN_DATA = 'POST_LOGIN_DATA';
export const POST_LOGIN_DATA_SUCCESS = 'POST_LOGIN_DATA_SUCCESS';
export const POST_LOGIN_DATA_FAILURE = 'POST_LOGIN_DATA_FAILURE';

export const POST_REGISTER_USER = 'POST_REGISTER_USER';
export const POST_REGISTER_USER_SUCCESS = 'POST_REGISTER_USER_SUCCESS';
export const POST_REGISTER_USER_FAILURE = 'POST_REGISTER_USER_FAILURE';

export const POST_ADD_USER = 'POST_ADD_USER';
export const POST_ADD_USER_SUCCESS = 'POST_ADD_USER_SUCCESS';
export const POST_ADD_USER_FAILURE = 'POST_ADD_USER_FAILURE';

export const POST_DELETE_USER = 'POST_DELETE_USER';
export const POST_DELETE_USER_SUCCESS = 'POST_DELETE_USER_SUCCESS';
export const POST_DELETE_USER_FAILURE = 'POST_DELETE_USER_FAILURE';

export const POST_ADD_BULK_IMPORT = 'POST_ADD_BULK_IMPORT';
export const POST_ADD_BULK_IMPORT_SUCCESS = 'POST_ADD_BULK_IMPORT_SUCCESS';
export const POST_ADD_BULK_IMPORT_FAILURE = 'POST_ADD_BULK_IMPORT_FAILURE';

export const POST_RESEND_ACTIVATION_EMAIL = 'POST_RESEND_ACTIVATION_EMAIL';
export const POST_RESEND_ACTIVATION_EMAIL_SUCCESS = 'POST_RESEND_ACTIVATION_EMAIL_SUCCESS';
export const POST_RESEND_ACTIVATION_EMAIL_FAILURE = 'POST_RESEND_ACTIVATION_EMAIL_FAILURE';

export const POST_CHANGE_PASSWORD = 'POST_CHANGE_PASSWORD';
export const POST_CHANGE_PASSWORD_SUCCESS = 'POST_CHANGE_PASSWORD_SUCCESS';
export const POST_CHANGE_PASSWORD_FAILURE = 'POST_CHANGE_PASSWORD_FAILURE';

export const POST_FORGOT_PASSWORD = 'POST_FORGOT_PASSWORD';
export const POST_FORGOT_PASSWORD_SUCCESS = 'POST_FORGOT_PASSWORD_SUCCESS';
export const POST_FORGOT_PASSWORD_FAILURE = 'POST_FORGOT_PASSWORD_FAILURE';

export const POST_RESET_PASSWORD = 'POST_RESET_PASSWORD';
export const POST_RESET_PASSWORD_SUCCESS = 'POST_RESET_PASSWORD_SUCCESS';
export const POST_RESET_PASSWORD_FAILURE = 'POST_RESET_PASSWORD_FAILURE';

export const POST_EDIT_PROFILE = 'POST_EDIT_PROFILE';
export const POST_EDIT_PROFILE_SUCCESS = 'POST_EDIT_PROFILE_SUCCESS';
export const POST_EDIT_PROFILE_FAILURE = 'POST_EDIT_PROFILE_FAILURE';

export const POST_ASSOCIATE_GENERAL_INFO = 'POST_ASSOCIATE_GENERAL_INFO';
export const POST_ASSOCIATE_GENERAL_INFO_SUCCESS = 'POST_ASSOCIATE_GENERAL_INFO_SUCCESS';
export const POST_ASSOCIATE_GENERAL_INFO_FAILURE = 'POST_ASSOCIATE_GENERAL_INFO_FAILURE';

export const POST_ASSOCIATE_DOCUMENT_UPLOAD = 'POST_ASSOCIATE_DOCUMENT_UPLOAD';
export const POST_ASSOCIATE_DOCUMENT_UPLOAD_SUCCESS = 'POST_ASSOCIATE_DOCUMENT_UPLOAD_SUCCESS';
export const POST_ASSOCIATE_DOCUMENT_UPLOAD_FAILURE = 'POST_ASSOCIATE_DOCUMENT_UPLOAD_FAILURE';

export const POST_ADMIN_ADDITIONAL_INFO = 'POST_ADMIN_ADDITIONAL_INFO';
export const POST_ADMIN_ADDITIONAL_INFO_SUCCESS = 'POST_ADMIN_ADDITIONAL_INFO_SUCCESS';
export const POST_ADMIN_ADDITIONAL_INFO_FAILURE = 'POST_ADMIN_ADDITIONAL_INFO_FAILURE';

export const POST_ADMIN_REJECT_ASSOCIATE = 'POST_ADMIN_REJECT_ASSOCIATE';
export const POST_ADMIN_REJECT_ASSOCIATE_SUCCESS = 'POST_ADMIN_REJECT_ASSOCIATE_SUCCESS';
export const POST_ADMIN_REJECT_ASSOCIATE_FAILURE = 'POST_ADMIN_REJECT_ASSOCIATE_FAILURE';