// GET METHODS

export const GET_PRODUCT_LIST = 'GET_PRODUCT_LIST';
export const GET_PRODUCT_LIST_SUCCESS = 'GET_PRODUCT_LIST_SUCCESS';
export const GET_PRODUCT_LIST_FAILURE = 'GET_PRODUCT_LIST_FAILURE';

export const GET_STATIC_DATA_PRODUCT = 'GET_STATIC_DATA_PRODUCT';
export const GET_STATIC_DATA_PRODUCT_SUCCESS = 'GET_STATIC_DATA_PRODUCT_SUCCESS';
export const GET_STATIC_DATA_PRODUCT_FAILURE = 'GET_STATIC_DATA_PRODUCT_FAILURE';

export const GET_PRODUCT_DATA = 'GET_PRODUCT_DATA';
export const GET_PRODUCT_DATA_SUCCESS = 'GET_PRODUCT_DATA_SUCCESS';
export const GET_PRODUCT_DATA_FAILURE = 'GET_PRODUCT_DATA_FAILURE';

export const GET_MODULE_LIST = 'GET_MODULE_LIST';
export const GET_MODULE_LIST_SUCCESS = 'GET_MODULE_LIST_SUCCESS';
export const GET_MODULE_LIST_FAILURE = 'GET_MODULE_LIST_FAILURE';

export const GET_MODULE_MAPPING_DATA = 'GET_MODULE_MAPPING_DATA';
export const GET_MODULE_MAPPING_DATA_SUCCESS = 'GET_MODULE_MAPPING_DATA_SUCCESS';
export const GET_MODULE_MAPPING_DATA_FAILURE = 'GET_MODULE_MAPPING_DATA_FAILURE';

export const GET_PRODUCT_MODULE_MAPPING = 'GET_PRODUCT_MODULE_MAPPING';
export const GET_PRODUCT_MODULE_MAPPING_SUCCESS = 'GET_PRODUCT_MODULE_MAPPING_SUCCESS';
export const GET_PRODUCT_MODULE_MAPPING_FAILURE = 'GET_PRODUCT_MODULE_MAPPING_FAILURE';

export const GET_INVERTER_LIST = 'GET_INVERTER_LIST';
export const GET_INVERTER_LIST_SUCCESS = 'GET_INVERTER_LIST_SUCCESS';
export const GET_INVERTER_LIST_FAILURE = 'GET_INVERTER_LIST_FAILURE';

export const GET_OPTIMIZER_LIST = 'GET_OPTIMIZER_LIST';
export const GET_OPTIMIZER_LIST_SUCCESS = 'GET_OPTIMIZER_LIST_SUCCESS';
export const GET_OPTIMIZER_LIST_FAILURE = 'GET_OPTIMIZER_LIST_FAILURE';

export const GET_PRODUCT_PART_LIST = 'GET_PRODUCT_PART_LIST';
export const GET_PRODUCT_PART_LIST_SUCCESS = 'GET_PRODUCT_PART_LIST_SUCCESS';
export const GET_PRODUCT_PART_LIST_FAILURE = 'GET_PRODUCT_PART_LIST_FAILURE';

export const GET_WAREHOUSE_LIST = 'GET_WAREHOUSE_LIST';
export const GET_WAREHOUSE_LIST_SUCCESS = 'GET_WAREHOUSE_LIST_SUCCESS';
export const GET_WAREHOUSE_LIST_FAILURE = 'GET_WAREHOUSE_LIST_FAILURE';

export const GET_WAREHOUSE_DATA = 'GET_WAREHOUSE_DATA';
export const GET_WAREHOUSE_DATA_SUCCESS = 'GET_WAREHOUSE_DATA_SUCCESS';
export const GET_WAREHOUSE_DATA_FAILURE = 'GET_WAREHOUSE_DATA_FAILURE';

export const GET_SUPPLIER_LIST = 'GET_SUPPLIER_LIST';
export const GET_SUPPLIER_LIST_SUCCESS = 'GET_SUPPLIER_LIST_SUCCESS';
export const GET_SUPPLIER_LIST_FAILURE = 'GET_SUPPLIER_LIST_FAILURE';

export const GET_SUPPLIER_DATA = 'GET_SUPPLIER_DATA';
export const GET_SUPPLIER_DATA_SUCCESS = 'GET_SUPPLIER_DATA_SUCCESS';
export const GET_SUPPLIER_DATA_FAILURE = 'GET_SUPPLIER_DATA_FAILURE';

export const GET_CONFIG_FIELDS_LIST = 'GET_CONFIG_FIELDS_LIST';
export const GET_CONFIG_FIELDS_LIST_SUCCESS = 'GET_CONFIG_FIELDS_LIST_SUCCESS';
export const GET_CONFIG_FIELDS_LIST_FAILURE = 'GET_CONFIG_FIELDS_LIST_FAILURE';

// POST METHODS
export const POST_SAVE_PRODUCT = 'POST_SAVE_PRODUCT';
export const POST_SAVE_PRODUCT_SUCCESS = 'POST_SAVE_PRODUCT_SUCCESS';
export const POST_SAVE_PRODUCT_FAILURE = 'POST_SAVE_PRODUCT_FAILURE';

export const POST_PRODUCT_IMAGE_UPLOAD = 'POST_PRODUCT_IMAGE_UPLOAD';
export const POST_PRODUCT_IMAGE_UPLOAD_SUCCESS = 'POST_PRODUCT_IMAGE_UPLOAD_SUCCESS';
export const POST_PRODUCT_IMAGE_UPLOAD_FAILURE = 'POST_PRODUCT_IMAGE_UPLOAD_FAILURE';

export const POST_DELETE_PRODUCT = 'POST_DELETE_PRODUCT';
export const POST_DELETE_PRODUCT_SUCCESS = 'POST_DELETE_PRODUCT_SUCCESS';
export const POST_DELETE_PRODUCT_FAILURE = 'POST_DELETE_PRODUCT_FAILURE';

export const POST_SAVE_MAPPING = 'POST_SAVE_MAPPING';
export const POST_SAVE_MAPPING_SUCCESS = 'POST_SAVE_MAPPING_SUCCESS';
export const POST_SAVE_MAPPING_FAILURE = 'POST_SAVE_MAPPING_FAILURE';


export const POST_SAVE_WAREHOUSE = 'POST_SAVE_WAREHOUSE';
export const POST_SAVE_WAREHOUSE_SUCCESS = 'POST_SAVE_WAREHOUSE_SUCCESS';
export const POST_SAVE_WAREHOUSE_FAILURE = 'POST_SAVE_WAREHOUSE_FAILURE';

export const POST_DELETE_WAREHOUSE = 'POST_DELETE_WAREHOUSE';
export const POST_DELETE_WAREHOUSE_SUCCESS = 'POST_DELETE_WAREHOUSE_SUCCESS';
export const POST_DELETE_WAREHOUSE_FAILURE = 'POST_DELETE_WAREHOUSE_FAILURE';

export const POST_SAVE_SUPPLIER = 'POST_SAVE_SUPPLIER';
export const POST_SAVE_SUPPLIER_SUCCESS = 'POST_SAVE_SUPPLIER_SUCCESS';
export const POST_SAVE_SUPPLIER_FAILURE = 'POST_SAVE_SUPPLIER_FAILURE';

export const POST_DELETE_SUPPLIER = 'POST_DELETE_SUPPLIER';
export const POST_DELETE_SUPPLIER_SUCCESS = 'POST_DELETE_SUPPLIER_SUCCESS';
export const POST_DELETE_SUPPLIER_FAILURE = 'POST_DELETE_SUPPLIER_FAILURE';

export const POST_SAVE_CONFIG_FIELDS = 'POST_SAVE_CONFIG_FIELDS';
export const POST_SAVE_CONFIG_FIELDS_SUCCESS = 'POST_SAVE_CONFIG_FIELDS_SUCCESS';
export const POST_SAVE_CONFIG_FIELDS_FAILURE = 'POST_SAVE_CONFIG_FIELDS_FAILURE';


